### ISSUE TITLE
Acquire Data for Preliminary Training

### ISSUE THREAD

**Issue by One2Remember** [grewe/covidID_fever#2]
Let's make a concerted effort to check out prior papers and see if we can email the authors to potentially acquire their data for our project. How useful that data will be in the long term for training is yet to be seen, but this could be a great starting point before we acquire our own data from the field

**Comment by One2Remember** [comment]
Made an email template for requesting datasets

**Comment by RohankumarM** [comment]
I tried reverse engineering the Flir one App and succeeded. So, now I think it might be possible to collect the data but not sure. Do we have the hardware? We could test it.

**Comment by One2Remember** [comment]
Reached out to several authors (listed here https://docs.google.com/document/d/197uSe1YZVfy5vFz6nfcd4dgUQeZNc8QZfwAJrRQobzA/edit)

Only one partial response so far, so let's hope we get more results this week
